<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Conqueror.Core/Conqueror.Core.csproj" />
    <ProjectReference Include="../../src/Conqueror.Game/Conqueror.Game.csproj" />
    <ProjectReference Include="../../src/Conqueror.Resources/Conqueror.Resources.csproj" />
  </ItemGroup>
</Project>
