<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="10.0.12" />
    <PackageReference Include="RefurbishedDinosaurs.LegacyFormats" Version="[$(RefurbishedDinosaursVersion)]" />
    <PackageReference Include="RefurbishedDinosaurs.Media.Smacker" Version="[$(RefurbishedDinosaursVersion)]" />
  </ItemGroup>
</Project>
