<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="RefurbishedDinosaurs.Core" Version="[$(RefurbishedDinosaursVersion)]" />
    <PackageReference Include="RefurbishedDinosaurs.Media.Audio" Version="[$(RefurbishedDinosaursVersion)]" />
    <PackageReference Include="RefurbishedDinosaurs.LegacyFormats" Version="[$(RefurbishedDinosaursVersion)]" />
    <PackageReference Include="RefurbishedDinosaurs.Media.Smacker" Version="[$(RefurbishedDinosaursVersion)]" />
  </ItemGroup>
</Project>
