<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="RefurbishedDinosaurs.Core" Version="1.1.0-preview.shared-runtime" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.12" />
    <PackageReference Include="RefurbishedDinosaurs.LegacyFormats" Version="1.1.0-preview.shared-runtime" />
    <PackageReference Include="RefurbishedDinosaurs.Media.Smacker" Version="1.0.0" />
  </ItemGroup>
</Project>
